# Generated by Django 5.1.6 on 2025-03-09 23:09

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Marca')),
            ],
        ),
        migrations.CreateModel(
            name='Operador',
            fields=[
                ('cedula', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Cédula')),
                ('nombre', models.CharField(max_length=25, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=25, verbose_name='Apellido')),
                ('telefono', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='VE', verbose_name='Teléfono')),
                ('correo', models.EmailField(max_length=100, verbose_name='Correo Electrónico')),
                ('direccion', models.TextField(verbose_name='Dirección')),
                ('independiente', models.BooleanField(default=True, verbose_name='Independiente')),
                ('foto_operador', models.ImageField(blank=True, null=True, upload_to='operadores/', verbose_name='Foto del Operador')),
            ],
        ),
        migrations.CreateModel(
            name='TipoMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Tipo de Material')),
            ],
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Modelo')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arpeta.marca', verbose_name='Marca')),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('placa', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Placa')),
                ('alto', models.DecimalField(decimal_places=2, default=0.0, max_digits=4, verbose_name='Alto (m)')),
                ('ancho', models.DecimalField(decimal_places=2, default=0.0, max_digits=4, verbose_name='Ancho (m)')),
                ('largo', models.DecimalField(decimal_places=2, default=0.0, max_digits=4, verbose_name='Largo (m)')),
                ('capacidad_carga', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Capacidad de Carga (m³)')),
                ('foto_vehiculo', models.ImageField(blank=True, null=True, upload_to='vehiculos/', verbose_name='Foto del Vehículo')),
                ('codigo_qr', models.ImageField(upload_to='codigos_qr/', verbose_name='Código QR')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arpeta.modelo', verbose_name='Modelo')),
            ],
        ),
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateField(verbose_name='Fecha de Asignación')),
                ('total_vueltas', models.IntegerField(default=0, verbose_name='Total de Vueltas')),
                ('total_material', models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Total de Material (m³)')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arpeta.operador', verbose_name='Operador')),
                ('tipo_material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='arpeta.tipomaterial', verbose_name='Tipo de Material')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arpeta.vehiculo', verbose_name='Vehículo')),
            ],
            options={
                'verbose_name': 'Asignacion',
                'verbose_name_plural': 'Asignaciones',
                'constraints': [models.UniqueConstraint(fields=('operador', 'vehiculo', 'fecha_asignacion'), name='unique_operador_vehiculo_fecha')],
            },
        ),
    ]
