# Generated by Django 5.1.5 on 2025-02-11 18:57

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camion',
            fields=[
                ('placa', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Placa')),
                ('modelo', models.CharField(max_length=50, verbose_name='Modelo')),
                ('alto', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Alto')),
                ('ancho', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Ancho')),
                ('largo', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Largo')),
                ('foto_camion', models.ImageField(blank=True, null=True, upload_to='camiones/', verbose_name='Foto del Camión')),
                ('codigo_qr', models.ImageField(blank=True, null=True, upload_to='codigos_qr/', verbose_name='Código QR')),
            ],
        ),
        migrations.CreateModel(
            name='Camionero',
            fields=[
                ('cedula', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Cédula')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=50, verbose_name='Apellido')),
                ('telefono', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='VE', verbose_name='Teléfono')),
                ('correo', models.EmailField(blank=True, max_length=100, null=True, verbose_name='Correo Electrónico')),
                ('direccion', models.TextField(blank=True, null=True, verbose_name='Dirección')),
                ('autonomo', models.BooleanField(default=True, verbose_name='Autónomo')),
                ('foto_camionero', models.ImageField(blank=True, null=True, upload_to='camioneros/', verbose_name='Foto de Perfil')),
            ],
        ),
        migrations.CreateModel(
            name='CamioneroCamion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateField(verbose_name='Fecha de Asignación')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('camion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arpeta.camion', verbose_name='Camión')),
                ('camionero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arpeta.camionero', verbose_name='Camionero')),
            ],
            options={
                'verbose_name': 'Relación Camionero-Camión',
                'verbose_name_plural': 'Relaciones Camionero-Camión',
                'constraints': [models.UniqueConstraint(fields=('camionero', 'camion'), name='unique_camionero_camion')],
            },
        ),
    ]
